# Generated by Django 5.2.3 on 2025-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('rpg_status', models.IntegerField(choices=[(1, 'Booking'), (2, 'Cancellation')])),
                ('room_id', models.IntegerField()),
                ('night_of_stay', models.DateField()),
            ],
        ),
    ]
