# Generated by Django 5.2.3 on 2025-06-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room_id',
            field=models.CharField(max_length=36),
        ),
    ]
