# Generated by Django 5.2.3 on 2025-06-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_provider', '0002_alter_event_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='original_event_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
