# Generated by Django 5.2.3 on 2025-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_provider', '0005_alter_event_original_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='original_event_id',
            field=models.BigIntegerField(),
        ),
    ]
